# Generated by Django 6.0.7 on 2026-08-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionconf',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subscription_conf_image'),
        ),
        migrations.AlterField(
            model_name='subscriptionconf',
            name='status_type',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive')], default='ACTIVE', max_length=8),
        ),
    ]
