# Generated by Django 6.0.7 on 2026-08-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscriptionconf_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionconf',
            old_name='title',
            new_name='subscription_conf_title',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status_type',
            field=models.CharField(default='sss', max_length=50),
        ),
    ]
