# Generated by Django 6.0.7 on 2026-08-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_rename_title_subscriptionconf_subscription_conf_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status_type',
            field=models.CharField(max_length=50),
        ),
    ]
