# Generated by Django 6.0.7 on 2026-09-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_subscription_status_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='slug',
            field=models.SlugField(default='sss'),
        ),
    ]
