# Generated by Django 6.0.7 on 2026-09-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_discount_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='slug',
            field=models.SlugField(),
        ),
    ]
