# Generated by Django 6.0.7 on 2026-09-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_alter_discount_code_alter_discount_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='discount',
            name='slug',
            field=models.SlugField(),
        ),
    ]
