# Generated by Django 6.0.7 on 2026-07-25 09:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('customer_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status_type', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_subscribe', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('comment_count', models.IntegerField(default=0)),
                ('subscription_count', models.IntegerField(default=0)),
                ('subscription_start_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_type', models.CharField(blank=True, choices=[(1, 'One month'), (3, 'Three months'), (6, 'Six months'), (12, 'Twelve months')], max_length=8, null=True)),
                ('like_count', models.IntegerField(default=0)),
                ('dislike_count', models.IntegerField(default=0)),
                ('active_device_count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
