# Generated by Django 6.0.7 on 2026-08-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_profile_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_path',
            field=models.CharField(max_length=300),
        ),
    ]
