# Generated by Django 6.0.7 on 2026-08-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customer_profile_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
