# Generated by Django 6.0.7 on 2026-08-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customer_profile_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='slug',
            field=models.SlugField(default='root', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[(1, 'One month'), (3, 'Three months'), (6, 'Six months'), (12, 'Twelve months')], max_length=1, null=True),
        ),
    ]
