# Generated by Django 6.0.7 on 2026-08-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customer_slug_alter_customer_subscription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
