# Generated by Django 6.0.7 on 2026-08-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customer_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_path',
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/%Y-%m-%d'),
        ),
    ]
