# Generated by Django 6.0.7 on 2026-08-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerlocation',
            name='banner_name',
            field=models.CharField(default='blank', max_length=200),
        ),
    ]
