# Generated by Django 6.0.7 on 2026-08-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_bannerlocation_banner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerlocation',
            name='banner_name',
            field=models.CharField(max_length=200),
        ),
    ]
