# Generated by Django 6.0.7 on 2026-08-03 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_alter_bannerlocation_banner_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='targetaudience',
            old_name='target',
            new_name='audience',
        ),
    ]
