# Generated by Django 6.0.7 on 2026-08-03 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_rename_target_targetaudience_audience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='bannerlocation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bannerlocation',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='country',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='country',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='informtype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='informtype',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='languagestatus',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='languagestatus',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='targetaudience',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='targetaudience',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='year',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='year',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='AccountStatus',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='BannerLocation',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='InformType',
        ),
        migrations.DeleteModel(
            name='LanguageStatus',
        ),
        migrations.DeleteModel(
            name='TargetAudience',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
