# Generated by Django 6.0.7 on 2026-08-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstatus',
            name='slug',
            field=models.SlugField(default='ssss', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='slug',
            field=models.SlugField(default='ssss', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='bannerlocation',
            name='slug',
            field=models.SlugField(default='ssss', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(default='ssss', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default='ssss', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='informtype',
            name='slug',
            field=models.SlugField(default='ssss', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='languagestatus',
            name='slug',
            field=models.SlugField(default='ssss', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='targetaudience',
            name='slug',
            field=models.SlugField(default='ssss', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='year',
            name='slug',
            field=models.SlugField(default='ssss', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='accountstatus',
            name='status',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='full_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='informtype',
            name='type',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='languagestatus',
            name='status',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='targetaudience',
            name='audience',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
