# Generated by Django 6.0.7 on 2026-08-05 18:59

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0008_alter_accountstatus_slug_alter_actor_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountstatus',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_account_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountstatus',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_account_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actor',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_actor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actor',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_actor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bannerlocation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_location', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bannerlocation',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_location', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='country',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_country', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_country', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='genre',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_genres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='genre',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_genres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='informtype',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_type', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='informtype',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_type', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='languagestatus',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_language', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='languagestatus',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_language', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='targetaudience',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_audience', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='targetaudience',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_audience', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='year',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_year', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='year',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_year', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_genre_name_case_insensitive'),
        ),
    ]
