# Generated by Django 6.0.7 on 2026-08-05 20:56

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0009_alter_accountstatus_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='accountstatus',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('status'), name='unique_account_status_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='actor',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('full_name'), name='unique_actor_name_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='bannerlocation',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('banner_name'), django.db.models.functions.text.Lower('location'), name='unique_banner_name_location_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_country_name_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='informtype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('type'), name='unique_inform_type_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='languagestatus',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('status'), name='unique_language_status_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='targetaudience',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('audience'), name='unique_target_audience_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='year',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('year'), name='unique_year_case_insensitive'),
        ),
    ]
