# Generated by Django 6.0.7 on 2026-08-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0010_accountstatus_unique_account_status_case_insensitive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerlocation',
            name='last_name',
        ),
        migrations.AddField(
            model_name='accountstatus',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actor',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bannerlocation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='country',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='genre',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='informtype',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='languagestatus',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='targetaudience',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='year',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
