# Generated by Django 6.0.7 on 2026-08-17 07:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0012_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
