# Generated by Django 6.0.7 on 2026-08-17 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_remove_content_colors'),
        ('tags', '0013_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
    ]
