# Generated by Django 6.0.7 on 2026-07-26 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('persian_name', models.CharField(max_length=100)),
                ('english_name', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('is_special_show', models.BooleanField(default=False)),
                ('release_year', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('imdb_rate', models.FloatField()),
                ('duration', models.IntegerField()),
                ('age_rate', models.IntegerField()),
                ('is_free', models.BooleanField(default=False)),
                ('is_special_list', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('satisfaction_avg', models.FloatField(default=0)),
                ('is_dubbed', models.BooleanField(default=False)),
                ('like_count', models.IntegerField(default=0)),
                ('dislike_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_content', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_content', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
