# Generated by Django 6.0.7 on 2026-08-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
