# Generated by Django 6.0.7 on 2026-08-08 21:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_is_deleted'),
        ('tags', '0012_director'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='content',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ContentActor',
            fields=[
                ('content_actor_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_actor', to='tags.actor')),
                ('content_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_actor', to='content.content')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_actor', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_actor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContentGenre',
            fields=[
                ('content_genre_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_genre', to='content.content')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_content_genre', to=settings.AUTH_USER_MODEL)),
                ('genre_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_genre', to='tags.genre')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_content_genre', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProducerCountry',
            fields=[
                ('producer_country_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_country', to='content.content')),
                ('country_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_country', to='tags.country')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_producer_country', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_product_country', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
