# Generated by Django 6.0.7 on 2026-08-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_content_created_by_alter_content_updated_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentactor',
            old_name='actor_uuid',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='contentactor',
            old_name='content_uuid',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='contentgenre',
            old_name='content_uuid',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='contentgenre',
            old_name='genre_uuid',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='producercountry',
            old_name='content_uuid',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='producercountry',
            old_name='country_uuid',
            new_name='country',
        ),
        migrations.AddField(
            model_name='content',
            name='status_type',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('INITIAL', 'Initial')], default='INITIAL', max_length=8),
        ),
        migrations.AddField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('M', 'Movie'), ('S', 'Series')], default='M', max_length=1),
        ),
    ]
