# Generated by Django 6.0.7 on 2026-08-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_contentactor_is_deleted_contentgenre_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='slug',
            field=models.SlugField(default='sss', max_length=100, unique=True),
        ),
    ]
