# Generated by Django 6.0.7 on 2026-08-15 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_content_slug'),
        ('tags', '0012_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentactor',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_actors', to='tags.actor'),
        ),
        migrations.AlterField(
            model_name='contentactor',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_actors', to='content.content'),
        ),
        migrations.AlterField(
            model_name='contentgenre',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_genres', to='content.content'),
        ),
        migrations.AlterField(
            model_name='contentgenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_genres', to='tags.genre'),
        ),
        migrations.AlterField(
            model_name='contentlanguagestatus',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_language_statuses', to='content.content'),
        ),
        migrations.AlterField(
            model_name='contentlanguagestatus',
            name='language_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_language_statuses', to='tags.languagestatus'),
        ),
        migrations.AlterField(
            model_name='producercountry',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_countries', to='content.content'),
        ),
        migrations.AlterField(
            model_name='producercountry',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_countries', to='tags.country'),
        ),
    ]
