# Generated by Django 6.0.7 on 2026-08-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_contentactor_actor_alter_contentactor_content_and_more'),
        ('tags', '0013_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='colors',
            field=models.ManyToManyField(to='tags.color'),
        ),
    ]
