# Generated by Django 6.0.7 on 2026-08-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_content_colors'),
        ('tags', '0013_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='content', to='tags.color'),
        ),
    ]
