# Generated by Django 6.0.7 on 2026-08-17 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_content_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='colors',
        ),
    ]
