# Generated by Django 6.0.7 on 2026-08-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_likedislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedislike',
            name='is_dislike',
        ),
        migrations.RemoveField(
            model_name='likedislike',
            name='is_like',
        ),
        migrations.AddField(
            model_name='likedislike',
            name='reaction',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], default='like', max_length=10),
        ),
    ]
