# Generated by Django 6.0.7 on 2026-08-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_remove_likedislike_is_dislike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislike',
            name='reaction',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10),
        ),
    ]
