# Generated by Django 6.0.7 on 2026-09-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_likedislike_unique_customer_content_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontent',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='video',
            field=models.FileField(default='sss', upload_to='videos/'),
        ),
    ]
