# Generated by Django 6.0.7 on 2026-09-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_videocontent_is_deleted_videocontent_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocontent',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
