# Generated by Django 6.0.7 on 2026-10-03 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_alter_videocontent_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.PositiveIntegerField()),
                ('file', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_videos', to='content.videocontent')),
            ],
            options={
                'unique_together': {('video_content', 'quality')},
            },
        ),
    ]
