# Generated by Django 6.0.7 on 2026-10-05 04:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_processedvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processedvideo',
            name='id',
        ),
        migrations.AddField(
            model_name='processedvideo',
            name='processed_video_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
