# Generated by Django 6.0.7 on 2026-10-05 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_remove_processedvideo_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocontent',
            name='status',
        ),
    ]
